# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-29 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10, unique=True)),
                ('sname', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('email', models.TextField(default='user@host.com')),
                ('wechat', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('pwd', models.CharField(max_length=20)),
                ('ismanager', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('sid',),
            },
        ),
    ]
