# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-30 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20190429_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('pname', models.CharField(max_length=50)),
                ('stime', models.DateField()),
                ('etime', models.DateField()),
                ('place', models.CharField(max_length=50)),
                ('pernum', models.PositiveIntegerField()),
                ('department', models.CharField(choices=[('01', '\u6587\u827a\u90e8'), ('02', '\u5b66\u672f\u90e8'), ('03', '\u4f53\u80b2\u90e8'), ('04', '\u5916\u8054\u90e8'), ('05', '\u56fd\u9645\u90e8'), ('06', '\u65b0\u5a92\u4f53\u4e2d\u5fc3'), ('07', '\u7ec4\u7ec7\u90e8'), ('08', '\u73ed\u8054\u90e8'), ('09', '\u5b9e\u8df5\u90e8'), ('10', '\u4fe1\u606f\u4e8b\u52a1\u90e8'), ('11', '\u76d1\u5bdf\u90e8')], max_length=2)),
                ('introduce', models.TextField()),
                ('link', models.TextField(blank=True)),
                ('checking', models.IntegerField(choices=[(0, '\u672a\u5ba1\u6838'), (1, '\u662f'), (2, '\u5426')], default=0)),
                ('borrow', models.IntegerField(choices=[(0, '\u672a\u5ba1\u6838'), (1, '\u662f'), (2, '\u5426')], default=0)),
            ],
            options={
                'ordering': ('pid',),
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Student'),
        ),
    ]
