# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-30 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20190430_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('aid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('reason', models.TextField()),
                ('money', models.FloatField()),
                ('checking', models.IntegerField(choices=[(0, '\u672a\u5ba1\u6838'), (1, '\u662f'), (2, '\u5426')], default=0)),
                ('stime', models.DateField(auto_now_add=True)),
                ('etime', models.DateField(null=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Project')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Student')),
            ],
            options={
                'ordering': ('stime', 'aid'),
            },
        ),
    ]
