# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='etime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='stime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
