# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-30 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20190430_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(0, '\u672a\u5f00\u59cb'), (1, '\u8fdb\u884c\u4e2d'), (2, '\u6210\u529f'), (3, '\u5931\u8d25')], default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, '\u672a\u5f00\u59cb'), (1, '\u8fdb\u884c\u4e2d'), (2, '\u6210\u529f'), (3, '\u5931\u8d25')], default=0),
        ),
    ]
