# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-09 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('01', '\u6587\u827a\u90e8'), ('02', '\u5b66\u672f\u90e8'), ('03', '\u4f53\u80b2\u90e8'), ('04', '\u5916\u8054\u90e8'), ('05', '\u56fd\u9645\u90e8'), ('06', '\u65b0\u5a92\u4f53\u4e2d\u5fc3'), ('07', '\u7ec4\u7ec7\u90e8'), ('08', '\u73ed\u8054\u90e8'), ('09', '\u5b9e\u8df5\u90e8'), ('10', '\u4fe1\u606f\u4e8b\u52a1\u90e8'), ('11', '\u76d1\u5bdf\u90e8'), ('12', '\u4e3b\u5e2d\u56e2')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department2',
            field=models.CharField(choices=[('01', '\u6587\u827a\u90e8'), ('02', '\u5b66\u672f\u90e8'), ('03', '\u4f53\u80b2\u90e8'), ('04', '\u5916\u8054\u90e8'), ('05', '\u56fd\u9645\u90e8'), ('06', '\u65b0\u5a92\u4f53\u4e2d\u5fc3'), ('07', '\u7ec4\u7ec7\u90e8'), ('08', '\u73ed\u8054\u90e8'), ('09', '\u5b9e\u8df5\u90e8'), ('10', '\u4fe1\u606f\u4e8b\u52a1\u90e8'), ('11', '\u76d1\u5bdf\u90e8'), ('12', '\u4e3b\u5e2d\u56e2')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='job',
            field=models.CharField(choices=[('\u5e72\u4e8b', '\u5e72\u4e8b'), ('\u526f\u90e8\u957f', '\u526f\u90e8\u957f'), ('\u90e8\u957f', '\u90e8\u957f'), ('\u526f\u4e3b\u5e2d', '\u526f\u4e3b\u5e2d'), ('\u4e3b\u5e2d', '\u4e3b\u5e2d')], max_length=10, null=True),
        ),
    ]
