# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-15 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_auto_20190509_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomrent',
            fields=[
                ('rid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('day', models.DateField()),
                ('room', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[(0, '\u6559\u5ba4'), (1, '\u4f1a\u8bae\u5ba4'), (2, '\u62a5\u544a\u5385')], max_length=10)),
                ('stime', models.CharField(max_length=8)),
                ('etime', models.CharField(max_length=8)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Project')),
            ],
        ),
    ]
