# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-15 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_roomrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrent',
            name='sid',
            field=models.ForeignKey(default='1650176', on_delete=django.db.models.deletion.CASCADE, to='mainsite.Student'),
        ),
    ]
