# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_roomrent_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrent',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Student'),
        ),
    ]
