# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-16 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_auto_20190716_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrent',
            name='status',
            field=models.IntegerField(choices=[(0, '\u672a\u5ba1\u6838'), (1, '\u662f'), (2, '\u5426')], default=0),
        ),
    ]
