# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-17 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0019_roomrent_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomrent',
            options={'ordering': ('day', 'rid')},
        ),
    ]
